// flow-typed signature: 6088dda4fee9a9a7c4f6c9c526f80607
// flow-typed version: <<STUB>>/append-css_v^0.1.6/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'append-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'append-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'append-css/browser/build' {
  declare module.exports: any;
}

declare module 'append-css/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'append-css/browser/build.js' {
  declare module.exports: $Exports<'append-css/browser/build'>;
}
declare module 'append-css/index' {
  declare module.exports: $Exports<'append-css'>;
}
declare module 'append-css/index.js' {
  declare module.exports: $Exports<'append-css'>;
}
declare module 'append-css/lib/index.js' {
  declare module.exports: $Exports<'append-css/lib/index'>;
}
