// flow-typed signature: 6d22e65bd5ac688ba04dfa1e925bf550
// flow-typed version: <<STUB>>/npm-run-help_v^1.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-run-help'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-run-help' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'npm-run-help/index' {
  declare module.exports: $Exports<'npm-run-help'>;
}
declare module 'npm-run-help/index.js' {
  declare module.exports: $Exports<'npm-run-help'>;
}
