// flow-typed signature: ad8aff0124662ffe8dc679b15dc190b5
// flow-typed version: <<STUB>>/npm-run-all_v^1.2.12/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-run-all'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-run-all' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-run-all/bin/help' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/main' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/npm-run-all' {
  declare module.exports: any;
}

declare module 'npm-run-all/bin/version' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/create-header' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/create-prefix-transform-stream' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/match-tasks' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/npm-run-all' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/read-package-json' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/run-task' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/run-tasks-in-parallel' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/run-tasks-in-sequencial' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/spawn-posix' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/spawn-win32' {
  declare module.exports: any;
}

declare module 'npm-run-all/lib/spawn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-run-all/bin/help.js' {
  declare module.exports: $Exports<'npm-run-all/bin/help'>;
}
declare module 'npm-run-all/bin/main.js' {
  declare module.exports: $Exports<'npm-run-all/bin/main'>;
}
declare module 'npm-run-all/bin/npm-run-all.js' {
  declare module.exports: $Exports<'npm-run-all/bin/npm-run-all'>;
}
declare module 'npm-run-all/bin/version.js' {
  declare module.exports: $Exports<'npm-run-all/bin/version'>;
}
declare module 'npm-run-all/index' {
  declare module.exports: $Exports<'npm-run-all'>;
}
declare module 'npm-run-all/index.js' {
  declare module.exports: $Exports<'npm-run-all'>;
}
declare module 'npm-run-all/lib/create-header.js' {
  declare module.exports: $Exports<'npm-run-all/lib/create-header'>;
}
declare module 'npm-run-all/lib/create-prefix-transform-stream.js' {
  declare module.exports: $Exports<'npm-run-all/lib/create-prefix-transform-stream'>;
}
declare module 'npm-run-all/lib/match-tasks.js' {
  declare module.exports: $Exports<'npm-run-all/lib/match-tasks'>;
}
declare module 'npm-run-all/lib/npm-run-all.js' {
  declare module.exports: $Exports<'npm-run-all/lib/npm-run-all'>;
}
declare module 'npm-run-all/lib/read-package-json.js' {
  declare module.exports: $Exports<'npm-run-all/lib/read-package-json'>;
}
declare module 'npm-run-all/lib/run-task.js' {
  declare module.exports: $Exports<'npm-run-all/lib/run-task'>;
}
declare module 'npm-run-all/lib/run-tasks-in-parallel.js' {
  declare module.exports: $Exports<'npm-run-all/lib/run-tasks-in-parallel'>;
}
declare module 'npm-run-all/lib/run-tasks-in-sequencial.js' {
  declare module.exports: $Exports<'npm-run-all/lib/run-tasks-in-sequencial'>;
}
declare module 'npm-run-all/lib/spawn-posix.js' {
  declare module.exports: $Exports<'npm-run-all/lib/spawn-posix'>;
}
declare module 'npm-run-all/lib/spawn-win32.js' {
  declare module.exports: $Exports<'npm-run-all/lib/spawn-win32'>;
}
declare module 'npm-run-all/lib/spawn.js' {
  declare module.exports: $Exports<'npm-run-all/lib/spawn'>;
}
