// flow-typed signature: 93e4e4880a88a4a4363ff6dc73ed682e
// flow-typed version: <<STUB>>/stylus_v^0.52.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylus/lib/browserify' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/fs' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/memory' {
  declare module.exports: any;
}

declare module 'stylus/lib/cache/null' {
  declare module.exports: any;
}

declare module 'stylus/lib/colors' {
  declare module.exports: any;
}

declare module 'stylus/lib/convert/css' {
  declare module.exports: any;
}

declare module 'stylus/lib/errors' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/image' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/resolver' {
  declare module.exports: any;
}

declare module 'stylus/lib/functions/url' {
  declare module.exports: any;
}

declare module 'stylus/lib/lexer' {
  declare module.exports: any;
}

declare module 'stylus/lib/middleware' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/arguments' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/atblock' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/atrule' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/binop' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/block' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/boolean' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/call' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/charset' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/comment' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/each' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/expression' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/extend' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/feature' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/function' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/group' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/hsla' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/ident' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/if' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/import' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/keyframes' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/literal' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/media' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/member' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/namespace' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/node' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/null' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/object' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/params' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/property' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/query-list' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/query' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/return' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/rgba' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/root' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/selector' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/string' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/supports' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/ternary' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/unaryop' {
  declare module.exports: any;
}

declare module 'stylus/lib/nodes/unit' {
  declare module.exports: any;
}

declare module 'stylus/lib/parser' {
  declare module.exports: any;
}

declare module 'stylus/lib/renderer' {
  declare module.exports: any;
}

declare module 'stylus/lib/stack/frame' {
  declare module.exports: any;
}

declare module 'stylus/lib/stack/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/stack/scope' {
  declare module.exports: any;
}

declare module 'stylus/lib/stylus' {
  declare module.exports: any;
}

declare module 'stylus/lib/token' {
  declare module.exports: any;
}

declare module 'stylus/lib/units' {
  declare module.exports: any;
}

declare module 'stylus/lib/utils' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/compiler' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/deps-resolver' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/evaluator' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/index' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/normalizer' {
  declare module.exports: any;
}

declare module 'stylus/lib/visitor/sourcemapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylus/index' {
  declare module.exports: $Exports<'stylus'>;
}
declare module 'stylus/index.js' {
  declare module.exports: $Exports<'stylus'>;
}
declare module 'stylus/lib/browserify.js' {
  declare module.exports: $Exports<'stylus/lib/browserify'>;
}
declare module 'stylus/lib/cache/fs.js' {
  declare module.exports: $Exports<'stylus/lib/cache/fs'>;
}
declare module 'stylus/lib/cache/index.js' {
  declare module.exports: $Exports<'stylus/lib/cache/index'>;
}
declare module 'stylus/lib/cache/memory.js' {
  declare module.exports: $Exports<'stylus/lib/cache/memory'>;
}
declare module 'stylus/lib/cache/null.js' {
  declare module.exports: $Exports<'stylus/lib/cache/null'>;
}
declare module 'stylus/lib/colors.js' {
  declare module.exports: $Exports<'stylus/lib/colors'>;
}
declare module 'stylus/lib/convert/css.js' {
  declare module.exports: $Exports<'stylus/lib/convert/css'>;
}
declare module 'stylus/lib/errors.js' {
  declare module.exports: $Exports<'stylus/lib/errors'>;
}
declare module 'stylus/lib/functions/image.js' {
  declare module.exports: $Exports<'stylus/lib/functions/image'>;
}
declare module 'stylus/lib/functions/index.js' {
  declare module.exports: $Exports<'stylus/lib/functions/index'>;
}
declare module 'stylus/lib/functions/resolver.js' {
  declare module.exports: $Exports<'stylus/lib/functions/resolver'>;
}
declare module 'stylus/lib/functions/url.js' {
  declare module.exports: $Exports<'stylus/lib/functions/url'>;
}
declare module 'stylus/lib/lexer.js' {
  declare module.exports: $Exports<'stylus/lib/lexer'>;
}
declare module 'stylus/lib/middleware.js' {
  declare module.exports: $Exports<'stylus/lib/middleware'>;
}
declare module 'stylus/lib/nodes/arguments.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/arguments'>;
}
declare module 'stylus/lib/nodes/atblock.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/atblock'>;
}
declare module 'stylus/lib/nodes/atrule.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/atrule'>;
}
declare module 'stylus/lib/nodes/binop.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/binop'>;
}
declare module 'stylus/lib/nodes/block.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/block'>;
}
declare module 'stylus/lib/nodes/boolean.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/boolean'>;
}
declare module 'stylus/lib/nodes/call.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/call'>;
}
declare module 'stylus/lib/nodes/charset.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/charset'>;
}
declare module 'stylus/lib/nodes/comment.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/comment'>;
}
declare module 'stylus/lib/nodes/each.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/each'>;
}
declare module 'stylus/lib/nodes/expression.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/expression'>;
}
declare module 'stylus/lib/nodes/extend.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/extend'>;
}
declare module 'stylus/lib/nodes/feature.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/feature'>;
}
declare module 'stylus/lib/nodes/function.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/function'>;
}
declare module 'stylus/lib/nodes/group.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/group'>;
}
declare module 'stylus/lib/nodes/hsla.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/hsla'>;
}
declare module 'stylus/lib/nodes/ident.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/ident'>;
}
declare module 'stylus/lib/nodes/if.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/if'>;
}
declare module 'stylus/lib/nodes/import.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/import'>;
}
declare module 'stylus/lib/nodes/index.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/index'>;
}
declare module 'stylus/lib/nodes/keyframes.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/keyframes'>;
}
declare module 'stylus/lib/nodes/literal.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/literal'>;
}
declare module 'stylus/lib/nodes/media.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/media'>;
}
declare module 'stylus/lib/nodes/member.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/member'>;
}
declare module 'stylus/lib/nodes/namespace.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/namespace'>;
}
declare module 'stylus/lib/nodes/node.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/node'>;
}
declare module 'stylus/lib/nodes/null.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/null'>;
}
declare module 'stylus/lib/nodes/object.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/object'>;
}
declare module 'stylus/lib/nodes/params.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/params'>;
}
declare module 'stylus/lib/nodes/property.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/property'>;
}
declare module 'stylus/lib/nodes/query-list.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/query-list'>;
}
declare module 'stylus/lib/nodes/query.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/query'>;
}
declare module 'stylus/lib/nodes/return.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/return'>;
}
declare module 'stylus/lib/nodes/rgba.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/rgba'>;
}
declare module 'stylus/lib/nodes/root.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/root'>;
}
declare module 'stylus/lib/nodes/selector.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/selector'>;
}
declare module 'stylus/lib/nodes/string.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/string'>;
}
declare module 'stylus/lib/nodes/supports.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/supports'>;
}
declare module 'stylus/lib/nodes/ternary.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/ternary'>;
}
declare module 'stylus/lib/nodes/unaryop.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/unaryop'>;
}
declare module 'stylus/lib/nodes/unit.js' {
  declare module.exports: $Exports<'stylus/lib/nodes/unit'>;
}
declare module 'stylus/lib/parser.js' {
  declare module.exports: $Exports<'stylus/lib/parser'>;
}
declare module 'stylus/lib/renderer.js' {
  declare module.exports: $Exports<'stylus/lib/renderer'>;
}
declare module 'stylus/lib/stack/frame.js' {
  declare module.exports: $Exports<'stylus/lib/stack/frame'>;
}
declare module 'stylus/lib/stack/index.js' {
  declare module.exports: $Exports<'stylus/lib/stack/index'>;
}
declare module 'stylus/lib/stack/scope.js' {
  declare module.exports: $Exports<'stylus/lib/stack/scope'>;
}
declare module 'stylus/lib/stylus.js' {
  declare module.exports: $Exports<'stylus/lib/stylus'>;
}
declare module 'stylus/lib/token.js' {
  declare module.exports: $Exports<'stylus/lib/token'>;
}
declare module 'stylus/lib/units.js' {
  declare module.exports: $Exports<'stylus/lib/units'>;
}
declare module 'stylus/lib/utils.js' {
  declare module.exports: $Exports<'stylus/lib/utils'>;
}
declare module 'stylus/lib/visitor/compiler.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/compiler'>;
}
declare module 'stylus/lib/visitor/deps-resolver.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/deps-resolver'>;
}
declare module 'stylus/lib/visitor/evaluator.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/evaluator'>;
}
declare module 'stylus/lib/visitor/index.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/index'>;
}
declare module 'stylus/lib/visitor/normalizer.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/normalizer'>;
}
declare module 'stylus/lib/visitor/sourcemapper.js' {
  declare module.exports: $Exports<'stylus/lib/visitor/sourcemapper'>;
}
